; Based on the Tauri CLI 2.11.3 PortugueseBR NSIS translations (MIT OR Apache-2.0).
; RF-DIS-001: labels only; maintenance/detection stays in the upstream template.
LangString addOrReinstall ${LANG_PORTUGUESEBR} "Reparar arquivos (manter os dados)"
LangString alreadyInstalled ${LANG_PORTUGUESEBR} "Instalação encontrada"
LangString alreadyInstalledLong ${LANG_PORTUGUESEBR} "${PRODUCTNAME} ${VERSION} já está instalado. Repare os arquivos ou desinstale o aplicativo."
LangString appRunning ${LANG_PORTUGUESEBR} "${PRODUCTNAME} está aberto. Feche o aplicativo e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESEBR} "${PRODUCTNAME} está aberto.$\nClique OK para fechá-lo antes de continuar."
LangString chooseMaintenanceOption ${LANG_PORTUGUESEBR} "Escolha a operação para esta instalação."
LangString choowHowToInstall ${LANG_PORTUGUESEBR} "Selecione Atualizar para manter seus dados."
LangString createDesktop ${LANG_PORTUGUESEBR} "Criar atalho na área de trabalho"
LangString dontUninstall ${LANG_PORTUGUESEBR} "Atualizar mantendo os dados"
LangString dontUninstallDowngrade ${LANG_PORTUGUESEBR} "Versão anterior sem desinstalar (indisponível)"
LangString failedToKillApp ${LANG_PORTUGUESEBR} "Não foi possível fechar ${PRODUCTNAME}. Feche o aplicativo e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESEBR} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão mais recente já está instalada. Cancele para mantê-la. Instalar esta versão anterior pode ser incompatível com seus dados."
LangString older ${LANG_PORTUGUESEBR} "mais antiga"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESEBR} "Versão anterior encontrada. Para instalar ${VERSION} e manter seus dados, selecione Atualizar mantendo os dados."
LangString silentDowngrades ${LANG_PORTUGUESEBR} "Instalar versão anterior está desabilitado nesse instalador, não foi possível proceder com a instalação silenciosa, por favor use a interface gráfica.$\n"
LangString unableToUninstall ${LANG_PORTUGUESEBR} "Não foi possível instalar!"
LangString uninstallApp ${LANG_PORTUGUESEBR} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESEBR} "Remover versão anterior e reinstalar"
LangString unknown ${LANG_PORTUGUESEBR} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESEBR} "Falha ao instalar WebView2! O programa não pode executar sem ele. Tente reiniciar o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESEBR} "Erro: Falha ao baixar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESEBR} "Bootstrapper do WebView2 baixado com sucesso"
LangString webview2Downloading ${LANG_PORTUGUESEBR} "Baixando o Bootstrapper do WebView2..."
LangString webview2InstallError ${LANG_PORTUGUESEBR} "Erro: Instalação do Webview2 falhou com código $1"
LangString webview2InstallSuccess ${LANG_PORTUGUESEBR} "WebView2 instalado com sucesso"
LangString deleteAppData ${LANG_PORTUGUESEBR} "Apagar também os dados do aplicativo"
